name: CI

on: [push, pull_request, workflow_dispatch]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Clone dependencies
      run: |
        # Use forked vial-gui with Keychron support
        git clone --branch vial-keychron https://github.com/tymon3310/vial-gui.git
        git clone https://github.com/vial-kb/via-keymap-precompiled.git
    - name: Cache emsdk
      id: cache-emsdk
      uses: actions/cache@v4
      with:
        path: emsdk
        key: emsdk-891b4491419c42f9d2b9f97c47d1043b26dfd3e5-3.1.10

    - name: Setup Emscripten
      if: steps.cache-emsdk.outputs.cache-hit != 'true'
      run: ./fetch-emsdk.sh

    - name: Cache built dependencies
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: deps
        key: deps-${{ hashFiles('version.sh') }}

    - name: Fetch sources
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: ./fetch-deps.sh

    - name: Build dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: ./build-deps.sh

    - name: Build vial-web
      run: |
        cd src
        ./build.sh
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: vial-web
        path: src/build

    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v4

    - name: Upload to Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: src/build

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
